name: kril_latin_bot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  path: ^1.8.0
  teledart: ^0.3.4
  translit: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
